name: CI
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: python:3.13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
      - name: enable corepack
        run: corepack enable
      - run: |
          docker buildx build  --output ./web/src/whl/ .
        shell: bash
      - name: Yarn
        run: |
          cd web
          yarn install
          yarn build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: webhorus.whl
          path: web/src/whl/*.whl
      - name: 'Upload Web Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: web/src/dist/**
  deploy:
    needs: build-package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download web
        uses: actions/download-artifact@v4
        with:
          name: web
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::143841941773:role/github
      - run: |
          aws s3 sync . s3://horus-dev.sondehub.org/ --delete
          aws s3 cp --content-type application/wasm ./assets/*.wasm s3://horus-dev.sondehub.org/assets/
          aws cloudfront create-invalidation --distribution-id E2BZ39U4B3U231  --paths '/*'
